<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('BD DEMO ')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <style type="text/css">
        </style>
        <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('bd_home') ?>"><?php echo $this->translate('Bd DEMO') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav'); ?>
                    <!--<ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('bd_home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>-->

                    <div class="collapse navbar-collapse pull-right col-md-4">
                        <ul class="nav navbar-nav">
                            <li><a href="<?php echo $this->url('bd_authentication_logout') ?>"><?php echo $this->translate('Log out') ?></a></li>
                        </ul>
                    </div>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container" style="padding-top:75px">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> Bd demo</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
